// INHERITANCE
import java.util.*;
import bank;

public class INHERITANCE {
    public static void main(String args[]) {
        bank.Account account1 = new bank.Account();
        account1.name = "customer1";
    }
}




















// class Shape {
//     String color;
// }

// class Triangle extends Shape {
    
// }

// public class INHERITANCE {
//     public static void main(String[] args) {
//         Triangle t1 = new Triangle();
//         t1.color = "red";
        
//         System.out.println(t1.color);
//     }
// }





// INHERITANCE => SINGLE LEVEL
// class Shape {
//   public void area() {
//       System.out.println("displays area");
//   }
// }

// class Triangle extends Shape {
//     public void area(int l, int h){
//         System.out.println(1/2*l*h);
//     }
// }



// public class INHERITANCE {
//   public static void main (String Args []) {
        
//     }
// }





// INHERITANCE => MULTI LEVEL
// class Shape {
//   public void area() {
//       System.out.println("displays area");
//   }
// }

// class Triangle extends Shape {
//     public void area(int l, int h){
//         System.out.println(1/2*l*h);
//     }
// }

// class EquilateralTriangle extends Triangle {
//     public void area(int l, int h){
//         System.out.println(1/2*l*h);
//     }
// }



// public class INHERITANCE {
//   public static void main (String Args []) {
        
//     }
// }





// INHERITANCE => HIERARCIAL INHERITANCE
// class Shape {
//     public void area() {
//         System.out.println("displays area");
//     }
//   }
  
//   class Triangle extends Shape {
//       public void area(int l, int h){
//           System.out.println(1/2*l*h);
//       }
//   }
  
//   class Circle extends Shape {
//       public void area(int r) {
//           System.out.println((3.142)*r*r);
//       }
//   }
  
  
  
//   public class INHERITANCE {
//     public static void main (String Args []) {
          
//       }
//   }





// INHERITANCE => HYBRID INHERITANCE





// INHERITANCE => MULTIPLE INHERITANCE(C++)
